### ISSUE TITLE
association of viral load with IFN in NS1-mutants

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/IFNsorted_flu_single_cell#25]
Elaborate on this observation. This point may involve adding some of Alistair's new data.

**Comment by abr28** [comment]
yes. Easy to add flow data. Can decide how best to show and go ahead and work it up again–2d flow + 1d flow perhaps? I know the NS1 threshold for staining is an issue, but I do have better controls if we want to use them from more recent analyses and have a thought on how to set a better NS1/HA staining trheshold to handle different dynamic ranges. That is a simple plot of HA freq vs NS1 freq and pick the asymptote wherein there is good association between the two. Threshold on only HA+ above that point, and then call NS1 +/- and IFN +/-. Can start to put together soon. 

Otherwise ribavirin by itself would be sufficient.
